- carla-spice-sync-service/SpiceUtils.cs
These details were mistakenly being grabbed from the legal entity where they should be coming off of the contact record
> Moved contact details retrieval off of legal entity

- cllc-public-app/openshift/templates/nginx-runtime/s2i/bin/run
See https://github.com/bcgov/TheOrgBook/pull/867
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Fixes string replacement for api service names with multiple slashes.

- cllc-interfaces/Dynamics-Autorest/Extensions/EntityDocumentExtensions.cs
- cllc-interfaces/Dynamics-Autorest/Extensions/FederalReportExportExtension.cs
- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMadoxioCannabismonthlyreport.cs
- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMsharepointdocumentlocation.cs
- cllc-interfaces/SharePoint/SharePointFileManager.cs
- cllc-public-app/Extensions/FileManagerClient.cs
- cllc-public-app/Startup.cs
- federal-reporting-service/FederalReportingController.cs
- federal-reporting-service/Startup.cs
- federal-reporting-service/federal-reporting-service.csproj
- file-manager-service/Services/FileManagerService.cs
This adds federal reporting export entities to keep track of monthly reports that are included in each report. It also allows admins to generate exports by creating a new export record.
This service now uses the File Manager Service for uploads to sharepoint
> New federal reporting exports

- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
do not create worker folder if the no wet signature feature is on.
> LCSD-3067 do not create worker folder if no wet signature

- cllc-public-app/ClientApp/src/app/components/applications/application-covid-temporary-extension/application-covid-temporary-extension.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-covid-temporary-extension/application-covid-temporary-extension.component.ts
Previous code was conflicting max length of 6 from mask and 7 from validation. Went with the smaller number as that was the limiter before. Error message now helps users
> validation message on licence # for covid

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licences.component.ts
- cllc-public-app/Controllers/AccountsController.cs
This removes the licences that an account is "deemed" so it will no longer show on a user's licence dashboard when they are being transferred a licence.
Is there a way for licencees to pay for a transfer? Right now I think they might just be getting lost as a transfer doesn't create an application
> LCSD-3549 - remove deemed licences

- cllc-interfaces/SharePoint/SharePointFileManager.cs
- cllc-public-app/Extensions/FileManagerClient.cs
- file-manager-service/Protos/fileManager.proto
- file-manager-service/Services/FileManagerService.cs
This PR adds logic to account for file name truncation that happens on SharePoint for long URLs
- `FileManagerService` was updated with additional gRPC endpoint
- Refactored truncation logic in `SharePointFileManager`
- Updated `FileManagerClient` to match changes to the gRPC service
> LCSD-3842 Account for filename truncation by SharePoint

- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.html
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.ts
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.html
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.scss
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.ts
- cllc-public-app/ClientApp/src/app/models/offsite-storage.model.ts
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Models.Extensions/OffsiteStorage.cs
- cllc-public-app/ViewModels/OffsiteStorage.cs
**Changes:**
- populate Date Removed when a location is Removed 
- hide the trash can icon when a location is removed 
- show "Removed" and "Active" instead of their status codes 
- use the Name field to provide a name of the location; 
- ensure the name cannot be longer than the field allows 
- make it mandatory 
- not available if licence Type is Catering or UBrew/UVin
**Styling:**
- Make the `+ Add location` button use the secondary button style 
- Make the `Cancel` button use the secondary button style
- if an item is removed, show the font in a grey text 
- wrap the contents of the page at around 1000px 
> LCSD-3968 Off-site storage fixes

- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.scss
* When form is shown in read-only mode, "Cancel Event" link has been replaced with "Return To Dashboard"
* The form is now up to UI standards (secondary button placement and styling fixes)
> LCSD-4177 Make market events application conform to UI standards

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- Make country fields **read-only**
- Replace text input on mailing address province with drop down of Canadian provinces and territories
> LCSD-4779 Fix mailing address in account profile page

- cllc-interfaces/SharePoint/SharePointFileManager.cs
- cllc-public-app/ClientApp/src/app/components/notices/notices.component.ts
- cllc-public-app/Controllers/FileController.cs
- file-manager-service/Services/FileManagerService.cs
This PR fixes the weird timestamps values we were seeing on the e-Notices page for the PDF files.
It now reflects the creation and last updated time from SharePoint (shown below)
> LCSD-4769 e-Notices Timestamps

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/policy-document/policy-document.component.ts
- cllc-public-app/ClientApp/src/app/components/worker-qualification/worker-home/worker-home.component.ts
- cllc-public-app/ClientApp/src/app/components/worker-qualification/worker-landing-page/worker-landing-page.component.html
- cllc-public-app/ClientApp/src/app/components/worker-qualification/worker-landing-page/worker-landing-page.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/worker-qualification/worker-landing-page/worker-landing-page.component.ts
- cllc-public-app/Controllers/FeaturesController.cs
**Deprecate Worker Qualification**
"Disable Worker Qualification" Feature Flag
* If enabled, replace the unauthenticated link to a new policy page document for worker information. hide the existing worker qualification pages.
* If someone navigates to https://justice.gov.bc.ca/cannabislicensing/policy-document/worker-qualification-training, then redirect them to the new route
> LCSD-5038 Deprecate worker qualification

- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/Controllers/LicensesController.cs
This PR fixes how we check for Agent licences. It was wrongly displaying the link to manage offsite storage to Agents.
It also fixes a small bug with third-party text in licence PDFs
> LCSD-5219 Manage offsite storage should not be available for Agent licences

- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
It was showing the phone number as "2505555555" instead of "(250) 555-5555"
> LCSD-5243 Show phone number in appropriate format

- cllc-public-app/ClientApp/src/app/components/servicecard-profile/servicecard-profile.component.html
- cllc-public-app/ClientApp/src/app/components/servicecard-profile/servicecard-profile.component.ts
**Changes:**
- When user logs in via BC Service Card, the primary address is set to read-only as service card manages the address as per drivers licence.
- If primary address is empty, then it is made editable to allow for changes
> LCSD-5494 Make primary address read-only for BC Service login

- lcrb-von-agent/docker/manage
- manage
- orgbook-issuer-agent/docker/manage
- orgbook-issuer-agent/issuer_pipeline/docker/build.sh
- Networking changes introduced in Docker 4.1.x and forward on Windows and MAC stop the direct use of the internal docker host IP returned by the `docker run --rm --net=host eclipse/che-ip` process. On Windows and MAC `host.docker.internal` needs to be used for internal connections between containers on separate docker networks.
- `host.docker.internal` has been available on Windows and Mac since Docker Engine version 18.03 (March 2018). Support for `host.docker.internal` on Linux was introduced in version 20.10.0 (2020-12-08), but it does not run out of the box yet (as of Docker Engine 20.10.11 (2021-11-17)). You need to add `--add-host=host.docker.internal:host-gateway` to the `docker run` command in order for it to work.
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> Add support for changes to internal Docker networking.

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
Adding validation if Temporary Use Area Endorsement does not contains hours of service
> LCSD-6134 C&E - TUA Event Authorization fixes required

- orgbook-service/openshift/templates/orgbook-service/orgbook-service.deploy.json
This is just to track the new variable in the template - the actual variable is in openshift as a secret. The template is still out of date
https://justice.gov.bc.ca/jira/browse/LCSD-6648
> added new variable to template

- cllc-public-app/Models.Extensions/License.cs
Fix for PDF generation issue. Cases such as "Closed" or empty values for hours in Dynamics were previously unhandled specifically for Endorsements, which led to failed PDF generation. Added catch to check if value of hours is equal to 845280096 (the Dynamics integer value of "Closed") or null. Verified that PDFs can be generated with correct hours.
> LCSD-7127: Fix for PDF generation issue.

- cllc-interfaces/BCEP/BCEPService.cs
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7153
Reason: BCEP PCIR has changed the /process_transaction.asp endpoint on their service from a GET to a POST request. Updating our API code to reflect this change. No other changes needed to implement PCIR besides updating the root URL of the request in OpenShift secrets.
> LCSD-7153: Update GET to POST for /process_transaction.asp

- cllc-interfaces/BCEP/BCEPService.cs
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7153
This pull request completes the PCIR work by enabling or disabling PCIR with a feature flag as a fallback in case the PCIR service fails. Three new environment variables will be added to our DEV, TEST, and PROD environments:
- PCIR_ENABLED: A true/false to enable or disable PCIR. Disabling PCIR causes the application to fall back to the old Bambora URL. Note that this is the only environment variable that needs to be changed in order to swap between PCIR and the old URL.
- BCEP_PCIR_SERVICE_URL: The base URL for the PCIR service
- BCEP_PCIR_SERVICE_VERIFY_URL: The base URL for the PCIR service - note that this will fall back to the value of BCEP_PCIR_SERVICE_URL in case this value is not defined. The values should be identical in …
> LCSD-7153: PCIR Implementation

- cllc-public-app/ClientApp/src/app/app.component.html
Follow-up from #4222.
Now that the maintenance event for 2024-07-31 is now complete, the outage banner must now be removed as per requested by the business area in [LCSD-7244](https://jag.gov.bc.ca/jira/browse/LCSD-7244).
> LCSD-7244: Remove outage banner for 2024-07-31 maintenance event

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.scss
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/environments/environment.ts
This pull request includes primarily work completed by Ross to get the Online Retailer Verification (ORV) ready to demo. Added a new box with a modal where a user can copy html code to paste into their website to trigger online verification.
Important notes:
- Currently, this will always copy BC123456 for demo purposes. In the near future this will be changed to use the existing BC registration ID for the retailer.
- Currently, the template for the html code is hardcoded in environment.ts. I would recommend building a config service such that we could fetch our openshift secrets from the API as Angular doesn't natively support runtime environment variables.
> LCSD-7126 Portal changes for ORV demo

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/proof-of-zoning/proof-of-zoning.component.html
Updated [multipleFiles] flag of app-file-uploader components to allow for multiple file uploads on Zoning and Proof of Valid Interest for both permanent and temporary relocations.
Screenshots:
> LCSD-7329: Multiple File Uploads for Zoning and Valid Interest

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.html
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
- cllc-public-app/ClientApp/src/app/models/application-license-summary.model.ts
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/ApplicationLicenseSummary.cs
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7328
This pull request improves on the existing temporary relocation application process, no longer relying on route state parameters to get license information, and instead just fetches the license based on the URL params. This removes possibilities that the user could end up on this page with no license information and ensures it is always fetched when the user hits the URL. 
Additionally, this PR adds Temporary Relocation Status - a property from Dynamics indicating whether the licensee is operating from a temporary location - to the payload for licenses, allowing us to disable the temporary relocation button on the relocation type form if the licensee is already operating from a temporary location. I have included a tooltip when the user …
> LCSD-7328: Conditionally Disable Temporary Relocation Application

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7327
This PR sets the following fields to blank if the application type is a temporary or permanent location transfer of a Licensee Retail Store:
- New Address Street
- New Address City
- New Address Postal Code
- New Address Parcel ID
- Local Government/Indigenous Nation
- Police Jurisdiction
Screenshots:
> LCSD-7327: New Address, LG/IN, Police fields default to blank for LRS Transfer of Location

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7275
Disallow illegal characters that cause issues with Sharepoint file/folder creation in company name change. Can be applied to other types of name changes (Person first/last name, addition of executor / receiver), but does not seem necessary as these characters very rarely appear in legal names of people.
> LCSD-7275: Disallow illegal characters in company name change

- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
Fixed an issue where the license object was missing specific required properties added in by the licenses and authorizations page. Opportunity for future improvement here - make these properties intrinsic to the license object on the backend so we don't have to process things in front-end components. 
Quick fix for now, reverting to old style of URL parameter passing to reduce amount of duplicate code. Added additional safeguard to navigate the user back to the licenses and authorizations page if no license object is present in the router state. This happens when a user refreshes on the relocation type page.
Added a couple more comments as well.
> LCSD-7328-Patch: Fix issue with processing relocation for LRS

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
Reverting change from business feedback to permanent-change-to-a-licensee.component.html. Component now displays the text that displayed before the changes were made.
> LCSD-7355: Revert permanent change to licensee notice

- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.html
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
Updates per comments on https://jag.gov.bc.ca/jira/browse/LCSD-7328
Temporary relocation applications will now be disabled if:
1. The licensee is currently operating from a temporary location, or
2. The license has an existing application for a temporary relocation with one of the following statuses:
- Submitted
- Incomplete/Info Req
- Pending LG/IN Approval
- Under Review
- Application Assessment
- AIP Issued
- Pending Final Inspection
- Reviewing Inspection Results
- Pending Licence Fee
If the license has a Temporary Relocation Application with the status is Approved, the licensee will be able to submit another temporary relocation application so long as they are not currently operating from a temporary location.
> LCSD-7328-Temp-Relo-Changes: Update criteria for disabling temp relo

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
This change adds a new 'Refund Policy' section for Liquor and Cannabis renewal applications as mentioned in https://jag.gov.bc.ca/jira/browse/LCSD-7414
The new checkbox is part of the validation so that the applicants are required to read and affirm the refund policy.
> LCSD-7414: Added refund policy for renewal applications

- cllc-public-app/ClientApp/src/app/components/policy-document/policy-document.component.html
- cllc-public-app/ClientApp/src/app/components/policy-document/policy-document.component.scss
Misleading/incorrect error message attribute not-found error to network
problem. Change this text to a simple "Page Not Found" text, and add
links to polices and bulletins. (provided by Coms)
> LCSD-6596 update error message for policy document

- cllc-public-app/ClientApp/src/app/components/sep/error-alert/error-alert.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/payment-confirmation/payment-confirmation.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
Also fixed an import on the `faPrint` icon that now displays a print icon.
> LCSD-7540: Increase text size and add margin to 'Print Page' on SEP Summary

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/package.json
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
The updates in this PR were using `npm audit fix` which automatically updates the packages that it can. This is generally quite safe but there is still a risk of something breaking. I have tested this locally and everything seems to be in order so far but we should definitely test this more on DEV.
> LCSD-6996: Version Updates

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-6276
Previously, the ownership details would generate an error message but did not set the form to invalid. This would allow form submissions without checking these declarations. I have added this validation and also a red asterisk to indicate that these are mandatory fields.
> LCSD-6279: Add Form Validation for Ownership Details

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
The `showValidInterestforTransfer()` did not include RLRS licence types which was preventing the drop box to show on the application. 
Jira Ticket: https://jira.justice.gov.bc.ca/browse/LCSD-7057
> LCSD-7057: Added Valid Interest to RLRS Licence Type

- cllc-public-app/Controllers/FeedbackController.cs
- cllc-public-app/Startup.cs
In our `Startup.cs`, there is a `Business-User` policy that checks if the current user has a `UserTypeClaim` with value of `Business`, but the users who log in using BC Services Card have the `userType` equal to `VerifiedIndividual`. This would explain why the call to the feedback controller was failing. 
Another interesting observation is that the SEP controller has the policy commented out, likely because it was failing due to this reason. If this fix is working in DEV, I will apply the new policy to the SEP controller as well. 
Jira Ticket: https://jira.justice.gov.bc.ca/browse/LCSD-7786
> LCSD-7786: Create Policy for BC Service Card Users

- cllc-public-app/Controllers/FeedbackController.cs
- cllc-public-app/Startup.cs
The new policy did not work as expected as the feedback submission from the SEP portal still resulted in a 403 error. However, we do not need to add the `[Authorize]` attribute as SiteMinder is configured to authenticate requests. It seems that this attribute is used to restrict certain content for different user types and is not needed in this controller.
> LCSD-7786: Revert New Policy and Remove it From Feedback Controller

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-7814
Noticed a bug where if you edited and saved the profile form, and re-loaded the page quickly, you would occasionally see the account url controls duplicated. It seems the subscription to fetch the form data occasionally emits twice, and the account urls were being added twice as a result. Only impacts array fields, since non-array fields just replace their value, rather than push into the array.
> BugFix: Duplicate Account URLs

- one-stop-service/Controllers/OneStopController.cs
- one-stop-service/OneStopUtils.cs
- one-stop-service/ReceiveFromHubService.cs
Changes made:
- Account Details Broadcast added to one stop status description drop down which can be used to manually trigger  AccountDetailsBroadcast.
- When portal receives a  CreateProgramAccountResponse it creates a one stop message item that will be picked up and added to the que by hangfire to send AccountDetailsBroadcast.
- AccountDetailsBroadcast Api addedto manually trigger response.
> LCSD-6537 One stop AccountDetailsBroadcast bug fix

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/OneStopHubStatusChangeType.cs
- one-stop-service/OneStopUtils.cs
Added missing code from which was causing an issue because AccountDetailsBroadcast was not included in  OneStopHubStatusChangeType.cs enum
> Onestop send account broadcast error

- cllc-public-app/ClientApp/.prettierignore
- cllc-public-app/ClientApp/src/app/components/tables/event-location-table/event-location-table.component.html
- cllc-public-app/ClientApp/src/app/components/tables/event-location-table/event-location-table.component.scss
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.scss
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
- cllc-public-app/ClientApp/src/app/models/endorsement.model.ts
- cllc-public-app/ClientApp/src/app/models/service-area.model.ts
- cllc-public-app/Models.Extensions/CapacityArea.cs
- cllc-public-app/ViewModels/CapacityArea.cs
https://jira.justice.gov.bc.ca/browse/LCSD-6680
- In the array of service area records, it now includes `endorsementId` for the related endorsement (if there is one).
- This is used to restrict which service area records are available to select in the form.
> LCSD-6680: FIx Temporary Use Area (TUA) Event form validation.

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Changes made when account has multiple urls or one that is not blank Generate Url is disabled.
> LCSD-7182: disable generate ovr button when account has url

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- https://jira.justice.gov.bc.ca/browse/LCSD-7801
- PR: https://github.com/bcgov/jag-lcrb-carla-public/pull/4430
- https://jira.justice.gov.bc.ca/browse/LCSD-7976
- PR: https://github.com/bcgov/jag-lcrb-carla-public/pull/4438
- This PR is a follow up to the above 2 linked tickets, and their PRs.
- It undoes all of the changes from PR #4438.
- It undoes part of the changes from PR #4430.
- Specifically, the bit of code around `transactionId`, `trnId`, and the `verify_payments` function.
- Why? There is an existing bug, that caused the payment details to now be shown, that I tried to fix, but it had some unintended consequences to the "Pay Now" button visibility. A fix will be still be needed for the payment details, but for now we are rolling back these changes in order to fix the "Pay …
> LCSD-7976-2: Revert SEP Payment Bug Fix

- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/ViewModels/Endorsement.cs
https://jira.justice.gov.bc.ca/browse/LCSD-6077
Fix: Inactive terms and conditions are no longer printed on the Licence.
Fix: Inactive service areas are no longer printed on the licence.
Fix: Inactive store hours are no longer printed on the licence.
> LCSD-6077: Don't Include Inactive Records on Licence PDF

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.html
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.html
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.ts
Changes To PCL:
-on validation fail on payment screen scrolls to nearest error.
-If the screen scrolls to tied house connection error and the panel is closed it will now open.
-Validation added to closed accordion with incomplete connections
Bug fix:
Bug fixed where TH connection was being saved with no associated licenses
> LCSD-8071: TH-UAT-Bug-16

- cllc-public-app/ClientApp/src/app/components/applications/legal-entity-review-permanent-change-to-a-licensee/legal-entity-review-permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/legal-entity-review-permanent-change-to-a-licensee/legal-entity-review-permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-payment/permanent-change-payment.component.html
- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-payment/permanent-change-payment.component.ts
- https://jira.justice.gov.bc.ca/browse/LCSD-8102
- https://jira.justice.gov.bc.ca/browse/LCSD-8105
- Add business rule to LE PCL to not charge for TH if TSE, TSI, or CoD also selected.
- Separated the `selectedChangeList` from the `paymentList` so that a separate list of changes can be shown in the change section vs the payment section.
- Updated both PCL and LE-PCL to use this.
> LCSD-8105: TH-UAT2-Bug-11
