- cllc-public-app/ClientApp/src/app/accordion/accordion.component.html
- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/result/result.component.html
- cllc-public-app/ClientApp/src/assets/survey-primary.json
- cllc-public-app/SeedData/Jurisdictions.json
> BC-308 Content Changes

- cllc-public-app/ClientApp/src/app/result/result.component.html
- cllc-public-app/Startup.cs
Add Security Headers to startup
> BC-365 Security Header

- cllc-public-app/Controllers/AdoxioApplicationController.cs
- cllc-public-app/Test/ApiIntegrationTestBaseWithLogin.cs
- cllc-public-app/Test/ApplicationTests.cs
- cllc-public-app/Test/LoginControllerTests.cs
Application controller and tests are w.i.p., checking in to hand off to developer.
> Updates to application controller and tests

- cllc-public-app/ClientApp/src/app/result/result.component.html
- cllc-public-app/ClientApp/src/assets/survey-primary.json
> BC-377 Content Changes

- cllc-interfaces/BCeID/BCeID.csproj
PR to remove the nuget dependency
> Remove dependency from BCeID project

- cllc-public-app/ClientApp/src/app/result/result.component.html
content changes for survey results
> BC-422 Content Changes

- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/ClientApp/src/app/edit-shareholders/edit-shareholders.component.ts
- cllc-public-app/Controllers/AccountController.cs
- cllc-public-app/Controllers/AdoxioLegalEntityController.cs
- cllc-public-app/Models.Extensions/Adoxio_LegalEntity.cs
Set attributes required for data records to show in Dynamics views.
> Set attributes required by Dynamics

- cllc-public-app-test/ApiIntegrationTestBaseWithLogin.cs
- cllc-public-app-test/LoginControllerTests.cs
- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
Update the dev login process to specify both user and business name (allows multi user per business).
Add unit test helper and unit tests for multi user under the same business (i.e. same account).
> Update Dev Login process to support Multi User per Business

- cllc-public-app-test/LegalEntityTests.cs
- cllc-public-app/ClientApp/src/app/bceid-confirmation/bceid-confirmation.component.html
- cllc-public-app/Controllers/AdoxioLegalEntityController.cs
Updated UI for Daniel
Also includes updated unit tests and email content.
> BCeID add options for specific business types

- cllc-public-app/ClientApp/src/app/bceid-confirmation/bceid-confirmation.component.html
- cllc-public-app/ClientApp/src/app/bceid-confirmation/bceid-confirmation.component.ts
- cllc-public-app/Controllers/AccountController.cs
- cllc-public-app/go-cllc.sh-template
Grant AllowAnon to websurge file.
Also misc bceid changes.
> Allow access to WebSurge file 

- cllc-public-app-test/ApiIntegrationTestBaseWithLogin.cs
Fix to the unit test base class for better data cleanup
> Updated logic for cleaning up unit test accounts

- cllc-public-app/Controllers/AccountController.cs
Clean up linked legal entity record (to support data cleanup in unit tests)
> Clean up legal entity when deleting account

- cllc-public-app/Controllers/AdoxioLegalEntityController.cs
> Comment out legal entity user validation for now

- cllc-public-app/ClientApp/src/app/license-application/tabs/store-information/store-information.component.html
> Store Information

- cllc-public-app-test/SecurityHelper.cs
- cllc-public-app-test/SecurityTests.cs
- cllc-public-app-test/SecurityUrlManglingTests.cs
- cllc-public-app/Controllers/AccountController.cs
Consolidate security unit tests into one test class and add tests.
> Security Unit Tests

- one-stop-service/Controllers/OneStopController.cs
- one-stop-service/OneStop/ProgramAccountRequest.cs
- one-stop-service/OneStopUtils.cs
- one-stop-service/ReceiveFromHubService.cs
- Correct malformed XML and other issues with communications
>  LCSD-439 - Fixes for issues with OneStopService

- cllc-public-app/Controllers/PaymentController.cs
Crash on payment for worker qualification
> LCSD-458: Add logging to investigate the issue

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMadoxioWorker.cs
- cllc-public-app/Controllers/ContactController.cs
LCSD-464
Fix Worker Creation on first login
> Worker qualification

- cllc-public-app/ClientApp/src/app/worker-qualification/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/worker-qualification/worker-application/worker-application.component.ts
LCSD-466
User can edit a Worker Qualification record after payment is done
> Worker qualification LCSD-466

- cllc-public-app-test/AliasTests.cs
- cllc-public-app-test/ApplicationTests.cs
- cllc-public-app-test/EstablishmentTests.cs
- cllc-public-app-test/FileTest.cs
- cllc-public-app-test/LegalEntityTests.cs
- cllc-public-app-test/PaymentControllerTests.cs
- cllc-public-app-test/PreviousAddressTests.cs
- cllc-public-app-test/SecurityTests.cs
- cllc-public-app-test/WorkerTests.cs
- cllc-public-app/Controllers/WorkerController.cs
- cllc-public-app/Models.Extensions/Worker.cs
- cllc-public-app/ViewModels/Worker.cs
> Worker qualification: LCSD-495  … Fix failing Dotnet tests

- cllc-public-app/ClientApp/src/app/payment-confirmation/payment-confirmation.component.html
modified cllc-public-app/ClientApp/src/app/payment-confirmation/payment-confirmation.component.html
> Removed payment confirmation message as per LCSD-1150

- cllc-public-app/ClientApp/src/app/application/application.component.html
- cllc-public-app/ClientApp/src/app/application/application.component.scss
- cllc-public-app/ClientApp/src/app/application/application.component.ts
- cllc-public-app/ClientApp/src/app/policy-document/policy-document.component.ts
Please note that there is indigenous nation content update in the PR. This will not affect anything as the flag is disabled
>  Fix policy documents in prod

- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.scss
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.ts
- pdf-service/Templates/cannabis_licence.mustache
Licence is Expired
Remove hours of sale from PDF licence
> LCSD-1816  and LCSD-1760 

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.spec.ts
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.spec.ts
- cllc-public-app/ClientApp/src/app/directives/remove-if-feature-off.directive.ts
- cllc-public-app/ClientApp/src/app/directives/remove-if-feature-on.directive.ts
- cllc-public-app/ClientApp/src/app/map/map.component.html
- cllc-public-app/ClientApp/src/app/services/account-data.service.ts
- cllc-public-app/ClientApp/src/app/services/feature-flag.service.ts
- cllc-public-app/ClientApp/src/app/services/feaure-guard.service.ts
- cllc-public-app/ClientApp/src/app/shared/account-picker/account-picker.component.html
- cllc-public-app/ClientApp/src/app/shared/account-picker/account-picker.component.spec.ts
- cllc-public-app/ClientApp/src/app/shared/account-picker/account-picker.component.ts
- cllc-public-app/Controllers/FeaturesController.cs
Feature flag for Map
Account picker UI component
> LCSD-1799 and LCSD-1028

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMadoxioLicences.cs
- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/application-ownership-transfer/application-ownership-transfer.component.html
- cllc-public-app/ClientApp/src/app/application-ownership-transfer/application-ownership-transfer.component.spec.ts
- cllc-public-app/ClientApp/src/app/application-ownership-transfer/application-ownership-transfer.component.ts
- cllc-public-app/ClientApp/src/app/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.scss
- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/associate-page/associate-page.component.html
- cllc-public-app/ClientApp/src/app/map/map.component.spec.ts
- cllc-public-app/ClientApp/src/app/models/application-license-summary.model.ts
- cllc-public-app/ClientApp/src/app/services/license-data.service.ts
- cllc-public-app/ClientApp/src/app/shared/product-inventory-packaged/product-inventory-packaged.component.spec.ts
- cllc-public-app/Controllers/FeaturesController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/ApplicationLicenseSummary.cs
>  LCSD-1752 … Write tooltips for renewals

- cllc-public-app/ClientApp/src/app/accordion/accordion.component.html
- cllc-public-app/ClientApp/src/app/application/application.component.html
- cllc-public-app/ClientApp/src/app/federal-reporting/federal-reporting.component.spec.ts
There is also a fix for angular unit tests
> LCSD-2074: content update. LCSD-2010: Sole prop supporting documents link

- cllc-public-app/ClientApp/src/app/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/models/application-license-summary.model.ts
- cllc-public-app/ClientApp/src/app/shared/licensee-tree/licensee-tree.component.html
- cllc-public-app/ClientApp/src/app/shared/licensee-tree/licensee-tree.component.scss
This includes an update to licensee changes
> LCSD-1976: Allow relocation after approval.

- lcrb-von-agent/docker/manage
- manage
- Refer to [von-network PR 82](https://github.com/bcgov/von-network/pull/82) for details.
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Update che-ip image reference

- cllc-public-app/ClientApp/src/app/shared/components/org-structure/org-structure.component.html
clarification from business SME
> public corporations do not provide shareholders

- functional-tests/bdd-tests/submit_application.feature
For review. Still working on this file.
> Revised feature file for LCSD-2466.

- cllc-interfaces/Dynamics-Autorest/Extensions/EntityDocumentExtensions.cs
- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/Controllers/FileController.cs
> Lcsd 2441 - Contact Folder Creation

- functional-tests/bdd-tests/CRSApplication.cs
- functional-tests/bdd-tests/CRSApplication.feature
- functional-tests/bdd-tests/submit_application.feature
Return CRSApplication.feature to the dashboard so we can transition to a scenario outline with multiple test cases. Fixed typo in submit_application.feature.
> Return CRSApplication.feature to the dashboard. Correct typo.

- cllc-public-app/ClientApp/src/app/components/worker-qualification/spd-consent/spd-consent.component.html
- cllc-public-app/ClientApp/src/app/components/worker-qualification/spd-consent/spd-consent.component.ts
- cllc-public-app/Models.Extensions/Worker.cs
- cllc-public-app/ViewModels/Worker.cs
Also Remove payment fields from common update service.
Payment fields are still updated by the payment controller.
> Remove consent validated from front end and common update service. 

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.html
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.scss
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.ts
- cllc-public-app/ClientApp/src/app/models/user.model.ts
- cllc-public-app/Controllers/EligibiltyController.cs
- cllc-public-app/Controllers/UserController.cs
- cllc-public-app/ViewModels/User.cs
This is the front end for the eligibility form - hidden behind a `FEATURE_ELIGIBILITY` flag
> eligibility form front end

- cllc-interfaces/Dynamics-Autorest/Extensions/DynamicsClient.cs
- cllc-interfaces/Dynamics-Autorest/Extensions/IDynamicsClient.cs
- cllc-public-app/Controllers/AccountsController.cs
- cllc-public-app/Controllers/LoginController.cs
- functional-tests/bdd-tests/CRSApplication.cs
- functional-tests/bdd-tests/CRSApplication.feature
- functional-tests/bdd-tests/TestBase.cs
Add code to guard against non-dev use of the account cleanup tool
> Improvements to automated CRS test cleanup.

- cllc-public-app/openshift/templates/nginx-runtime/Dockerfile
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Fix file and folder permissions on nginx-runtime

- cllc-public-app/ClientApp/src/app/components/licences/licences.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licences.component.ts
handle zero licences on licence dashboard
> handle zero licences on licence dashboard

- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/Contexts/DynamicsExtensions.cs
… where there is a name match but not a guid match.
> LCSD-2943 Add support for a contact & account lookup in a case 

- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/security-screening-requirements/security-screening-requirements.component.html
- cllc-public-app/ClientApp/src/app/components/security-screening-requirements/security-screening-requirements.component.scss
- cllc-public-app/ClientApp/src/styles.scss
- Improve styling on security screening page
- fix bug on application dashboard for renewals
> LCSD-2991 & LCSD-2992

- cllc-public-app/ClientApp/src/app/components/applications/application-licensee-changes/application-licensee-changes.component.html
when the user must pay a fee due to their licensee change application, there is now a section that appears to make it more obvious.
> added section to indicate fees are required LCSD-3030

- cllc-public-app/Controllers/FileController.cs
> Adjust session checks so that they only happen for URLs that have

- lcrb-von-agent/lcrb-von-agent/config/services.yml
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
This updates a few of the schema mappings to store the address in the OrgBook address table.
@brianorwhatever
> Update address in schema for new aca-py/indy catalyst version of orgbook

- cllc-public-app/ClientApp/src/app/components/applications/application-covid-temporary-extension/application-covid-temporary-extension.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-covid-temporary-extension/covid-confirmation/covid-confirmation.component.html
as per meeting with Michelle Roberts
> content review

- cllc-interfaces/BCEP/BCEPService.cs
- cllc-public-app/Contexts/DynamicsExtensions.cs
Add alternate hash key, fix logic for isLiquor.
> LCSD-3512 - second merchant account

- cllc-public-app/ClientApp/src/app/components/applications/application-licensee-changes/application-licensee-changes.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/models/application-summary.model.ts
- cllc-public-app/ClientApp/src/app/models/application.model.ts
- cllc-public-app/ClientApp/src/app/models/licensee-change-log.model.ts
- cllc-public-app/ClientApp/src/app/shared/components/associate-list/associate-list.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/licensee-tree/licensee-tree.component.ts
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/ViewModels/Application.cs
- cllc-public-app/ViewModels/ApplicationSummary.cs
Also Include fix for deleting licensee changes
> Fix flow for free endorsement application

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
Replaced min/max length validation with regular expression to account first digit being non-zero
> LCSD-4035 Fix validation of CRA business numbers

- cllc-interfaces/Dynamics-Autorest/Extensions/EntityDocumentExtensions.cs
- cllc-public-app/Controllers/LicenceEventsController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Controllers/WorkerController.cs
- cllc-public-app/Extensions/FileManagerClient.cs
- cllc-public-app/Models.Extensions/FileSystemItem.cs
- cllc-public-app/Utils/HashUtility.cs
We need to save copies of the authorization letter, or the produced licence in a folder in SharePoint.
**Software Design:**
* Create a common function that will be called from the licence and worker portions of the code, at time of PDF generation, to save a copy into SharePoint.
**Process for generating:**
* Take hash of data
* Save as file name - file name is based on the hash
* When something changes and the download is done again, would create a new one
* Where to save
* Send to SharePoint after download
* Handle read/write issues with SharePoint
* Timestamp of modified date will suffice
> LCSD-3842 Auto-save generated PDFs

- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.ts
> LCSD-4088 Market Events: Make Street Address 1 required

- cllc-interfaces/Dynamics-Autorest/Extensions/EntityDocumentExtensions.cs
- cllc-interfaces/PDF/IPdfService.cs
- cllc-interfaces/PDF/PdfService.cs
- cllc-public-app/Controllers/LicenceEventsController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Controllers/WorkerController.cs
- cllc-public-app/Extensions/FileManagerClient.cs
- cllc-public-app/Models.Extensions/FileSystemItem.cs
- pdf-service/Controllers/PDFController.cs
- pdf-service/Readme.md
- pdf-service/Utils/HashUtility.cs
- Refactored code to support hashing at the PDF Service level
- Fixed a couple small bugs I found while implementing this feature
> LCSD-3842 Saving generated PDFs

- cllc-interfaces/Dynamics-Autorest/Extensions/EntityDocumentExtensions.cs
- cllc-public-app/Controllers/LicenceEventsController.cs
- cllc-public-app/Controllers/WorkerController.cs
- cllc-public-app/Extensions/FileManagerClient.cs
Save the files to the correct sharepoint location and improve the hash checking logic
> LCSD-3842 Save PDFs to correct location

- cllc-public-app/Models.Extensions/LicenceEvent.cs
- Use new fields with right date configuration in Dynamics
@GeorgeWalker we need to test this code in DEV (Openshift) and the only way I can think of is via a code merge. If it doesn't resolve the bug we can revert the commit
> LCSD-4051 Date BUG

- cllc-public-app/Controllers/ContactController.cs
- cllc-public-app/Controllers/LegalEntitiesController.cs
> LCSD-4303 fix for null exception

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMadoxioOffsitestorage.cs
- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.html
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.scss
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.ts
- cllc-public-app/ClientApp/src/app/components/tables/capacity-table.component.ts
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.html
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.scss
- cllc-public-app/ClientApp/src/app/components/tables/offsite-table/offsite-table.component.ts
- cllc-public-app/ClientApp/src/app/models/application-license-summary.model.ts
- cllc-public-app/ClientApp/src/app/models/license.model.ts
- cllc-public-app/ClientApp/src/app/models/offsite-storage.model.ts
- cllc-public-app/ClientApp/src/app/services/license-data.service.ts
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/Models.Extensions/OffsiteStorage.cs
- cllc-public-app/ViewModels/ApplicationLicenseSummary.cs
- cllc-public-app/ViewModels/License.cs
- cllc-public-app/ViewModels/OffsiteStorage.cs
Initial PR to be able to demo Off-Site Storage form to stakeholders. 
More work needed for cleanup/enhancements
> LCSD-3968 Offsite Storage

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/MicrosoftDynamicsCRMaccount.cs
Fixes `DateTimeOffset` serialization error
> Remove extra annotations for "adoxio_datesignordismissed"

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/package.json
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/federal-reporting/product-inventory-sales-report/product-inventory-sales-report.component.html
The updated library fixes the bug. 
For reference it was also reported [here](https://github.com/JsDaddy/ngx-mask/issues/736)
> LCSD-4262 Upgrade ngx-mask dependency to fix issue with fractional values

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
This PR allows applicants to select a province other than BC for their main address.
> LCSD-3166 allow out of province addresses for applicants

- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.html
- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.scss
This PR improves styling and UI consistency for catering event applications.
> LCSD-4531 Improve styling for catering events

- cllc-public-app/ClientApp/src/app/components/tables/capacity-table.component.html
- cllc-public-app/ClientApp/src/app/components/tables/capacity-table.component.ts
> LCSD-4672 Fix text rendering bug

- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
> LCSD-4709 disable LDB orders when licence type is Manufacturer

- cllc-interfaces/Dynamics-Autorest/Extensions/DynamicsClient.cs
- cllc-interfaces/Dynamics-Autorest/Extensions/EventsExtension.cs
- cllc-interfaces/Dynamics-Autorest/Extensions/IDynamicsClient.cs
- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.ts
- cllc-public-app/ClientApp/src/app/components/temporary-offsite/temporary-offsite.component.ts
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.scss
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
- cllc-public-app/ClientApp/src/app/models/licence-event-schedule.ts
- cllc-public-app/ClientApp/src/app/models/licence-event.model.ts
- cllc-public-app/ClientApp/src/app/shared/date-fns.ts
- cllc-public-app/ClientApp/src/app/shared/form-base.ts
- cllc-public-app/ClientApp/src/styles.scss
- cllc-public-app/Controllers/FeaturesController.cs
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/Models.Extensions/CapacityArea.cs
- cllc-public-app/Models.Extensions/LicenceEvent.cs
- cllc-public-app/Models.Extensions/LicenceEventLocation.cs
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/Models.Extensions/ServiceArea.cs
- cllc-public-app/ViewModels/ApplicationLicenseSummary.cs
- cllc-public-app/ViewModels/Endorsement.cs
- cllc-public-app/ViewModels/LicenceEvent.cs
- cllc-public-app/ViewModels/LicenceEventLocation.cs
- cllc-public-app/ViewModels/License.cs
First pass at a "workable" TUA events form. Needed to demo stakeholders
> LCSD-4628 TUA events

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
> LCSD-4779 Fix missing country field in application form

- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
Allows federal reports to be submitted for Section 119 Authorization licenses
> Fix for LCSD-4754 Section 119 federal reports

- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/federal-reporting/product-inventory-sales-report/product-inventory-sales-report.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/product-inventory-sales-report/product-inventory-sales-report.component.ts
It also cleans up the code by removing an unnecessary array search every time we want to check if an inventory form should be displayed or not.
> Fix checkbox behaviour in federal reports form

- cllc-public-app/ClientApp/src/app/services/license-data.service.ts
- cllc-public-app/Controllers/LicensesController.cs
This fixes a server error for T&C changes applications
> LCSD-4847 Fix for application type on URL path

- cllc-public-app/ClientApp/src/app/components/tables/capacity-table-row.component.ts
> LCSD-4711 service area logic improvements

- cllc-public-app/ClientApp/src/app/components/applications/application-ownership-transfer/application-ownership-transfer.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
Small PR with content updates and formatting fixes.
> LCSD-4118, LCSD-4793 Formatting and content fixes

- cllc-public-app/Controllers/LicenceEventsController.cs
- cllc-public-app/Controllers/LicensesController.cs
> LCSD-4810 Fix date bug on Catering Authorization PDF

- carla-spice-sync-service/SpiceUtils.cs
- cllc-public-app/Contexts/DynamicsExtensions.cs
- cllc-public-app/Controllers/LEConnectionsController.cs
> Exclude inactive LE Connections from security screening

- cllc-public-app/ClientApp/src/app/components/applications/application-ownership-transfer/application-ownership-transfer.component.ts
> LCSD-4760 Allow licence transfer even if the target licensee has no primary contact

- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.scss
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/Controllers/MonthlyReportsController.cs
> LCSD-4994 UX improvements for Federal Reports page

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licences.component.ts
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.html
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.scss
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.ts
- cllc-public-app/ClientApp/src/app/models/licence-event.model.ts
- cllc-public-app/Controllers/FeaturesController.cs
* New form to request authorization for **All Ages Liquor Free** events
* Only for **Liquor Primary** and **Liquor Primary Club** licensees
* Feature flag `FEATURE_LIQUOR_FREE_EVENTS` needs to be set to enable this form
* Liquor Free events are auto-approved
* No authorization letter is generated
> LCSD-5029 Liquor Free Events

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.scss
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-ownership-transfer/application-ownership-transfer.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-ownership-transfer/application-ownership-transfer.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/application-ownership-transfer/application-ownership-transfer.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-third-party-operator/application-third-party-operator.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-third-party-operator/application-third-party-operator.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/application-third-party-operator/application-third-party-operator.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.scss
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.html
- cllc-public-app/ClientApp/src/app/components/eligibility-form/eligibility-form.component.scss
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.scss
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.ts
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.scss
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.scss
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
This PR refactors several existing forms to follow the standard button layout pattern
> LCSD-4771 Button layout fixes

- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/product-inventory-sales-report/product-inventory-sales-report.component.html
> LCSD-4993 Verbiage update on federal reporting form

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.scss
- cllc-public-app/ClientApp/src/app/app.component.ts
> LCSD-5103 Show warning badge for e-Notices

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
> LCSD-5076 RLRL application styling fixes

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licences.component.ts
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.ts
- cllc-public-app/ClientApp/src/app/components/take-home-event/take-home-event.component.html
- cllc-public-app/ClientApp/src/app/components/take-home-event/take-home-event.component.scss
- cllc-public-app/ClientApp/src/app/components/take-home-event/take-home-event.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/take-home-event/take-home-event.component.ts
- cllc-public-app/ClientApp/src/app/models/licence-event.model.ts
- cllc-public-app/Controllers/FeaturesController.cs
> LCSD-3823 Take Home Sampling Events

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
Make sure that renewal applications go through the account profile
> LCSD-5298 Make sure that renewal applications go through the account profile

- cllc-public-app/ClientApp/src/app/components/tables/capacity-table-row.component.html
> LCSD-5065 Expand service area capacity to 5 digits

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
* On the Account Profile page, modify the **Corporation Contact** to always update the contact record of the logged in Contact (is currently saved to "Primary Contact")
* First Name / Last Name are now read-only; must be updated at BCeID
> LCSD-5372 Update Account Profile for Business BCeID

- cllc-public-app/ClientApp/src/app/components/security-screening-requirements/security-screening-requirements.component.html
- cllc-public-app/Controllers/LEConnectionsController.cs
- cllc-public-app/ViewModels/SecurityScreeningStatusItem.cs
The DOB field in the portal now match what is stored in Dynamics
> LCSD-5366 Security screening page shows incorrect DOB for associates

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.scss
* Clicking on the user name takes you to the Account Profile page
> LCSD-5375 Make User Name link to Account Profile

- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-confirmation/servicecard-user-confirmation.component.html
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-confirmation/servicecard-user-confirmation.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-confirmation/servicecard-user-confirmation.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-terms-and-conditions/servicecard-user-terms-and-conditions.component.html
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-terms-and-conditions/servicecard-user-terms-and-conditions.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-terms-and-conditions/servicecard-user-terms-and-conditions.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/sep/servicecard-user-terms-and-conditions/servicecard-user-terms-and-conditions.component.ts
> LCSD-5493 Contact creation when logging into SEP dashboard

- cllc-public-app/ClientApp/src/app/components/bceid-confirmation/bceid-confirmation.component.ts
- cllc-public-app/ViewModels/AdoxioLegalEntity.cs
> LCSD-5643 Police Accounts

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/approval-settings/approval-settings.component.html
- cllc-public-app/ClientApp/src/app/components/police-representative/approval-settings/approval-settings.component.scss
- cllc-public-app/ClientApp/src/app/components/police-representative/approval-settings/approval-settings.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/approval-settings/approval-settings.component.ts
- cllc-public-app/ClientApp/src/app/components/user-menu/user-menu.component.html
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/ClientApp/src/app/services/police-auth-guard.service.ts
- cllc-public-app/Models.Extensions/Account.cs
- cllc-public-app/ViewModels/Account.cs
> LCSD-5595 Police Approval Settings

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/navbar/police-nav/police-nav.component.html
- cllc-public-app/ClientApp/src/app/components/police-representative/all-applications/all-applications.component.html
- cllc-public-app/ClientApp/src/app/components/police-representative/all-applications/all-applications.component.scss
- cllc-public-app/ClientApp/src/app/components/police-representative/all-applications/all-applications.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/all-applications/all-applications.component.ts
- cllc-public-app/ClientApp/src/app/models/sep-application-summary.model.ts
- cllc-public-app/ClientApp/src/app/services/index-db.service.ts
- cllc-public-app/ClientApp/src/app/services/special-events-data.service.ts
- cllc-public-app/Models.Extensions/SpecialEvent.cs
- cllc-public-app/ViewModels/SpecialEvent.cs
> LCSD-5609 Police All Applications page

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/liquor/liquor.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ViewModels/SpecialEvent.cs
Include the ability to transition from liquor step to summary
> SEP summary update

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/sep-application.component.ts
- cllc-public-app/Controllers/SpecialEventsController.cs
> Update route security and fix application creation

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
Changed the behavior of the sep summary submit button to redirect to the /sep/my-applications page (with a confirmation message showing submission is successful)  if the status after submission is not "Approved" or "Pending Review"
> LCSD-6210 improve UX after sep application submission

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Updated Hours Validation Logic to account for Open of Day before if close before open on Day.
> LSCD5852-Updated Hours Validation Logic

- cllc-public-app/ClientApp/src/app/components/home/home.component.html
- cllc-public-app/ClientApp/src/app/components/sep/login/login.component.html
- cllc-public-app/ClientApp/src/app/components/sep/login/login.component.scss
updated login disabled messed, added to SEP
> updated login disabled message, added to SEP

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/src/app/components/home/home.component.html
- cllc-public-app/ClientApp/src/app/components/sep/login/login.component.html
- cllc-public-app/ClientApp/src/app/components/sep/login/login.component.scss
Merging Develop to Master for UAT
> Merging Develop to Master for UAT

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Updated Application form to flag Proposed Establishment Name as required
> LCSD-5262 Updated Application form to flag Proposed Establishment Name as required

- cllc-public-app/ClientApp/.s2i/bin/assemble
Reverts bcgov/jag-lcrb-carla-public#3645
Did not fix build
> Revert "Fix Build - Replace depricated --prod and remove --deploy-Url (alread…"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#3642
> Revert "LCSD-6132:  Updated the list for which holdOtherManufacturerLicense q…"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#3652
>  "LCSD-6132:  Updated the list for which holdOtherManufacturerLicense q…""

- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
1. don't disable Dashboard function.
2. disable renewal licenses only.
> LCSD-6388 requirement update.

- cllc-public-app/ClientApp/src/app/components/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-fee-payment-confirmation/licence-fee-payment-confirmation.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-fee-payment-confirmation/licence-fee-payment-confirmation.component.ts
- cllc-public-app/Controllers/PaymentController.cs
- LCSD-6417 - Added invoice description to the licence fee payment confirmation page
- LCSD-6420 - Updated wording on outstanding balances table
> LCSD-6417 + LCSD-6420 - Add invoice description and update outstanding balance table wording

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.ts
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- LCSD-6433 - Add federal reporting functionality for PRS
- LCSD-6453 - Change wording on Connection to Producers section for PRS licences and S119 PRS Authorizations
> Add federal reporting for PRS, add alternate wording to connection-to-producers component

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
Issue found while testing LCSD-6448
> Update "Production" to "Producer" on renewal application

- cllc-public-app/ClientApp/src/app/components/police-representative/police-grid-approved/police-grid-approved.component.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/police-grid-denied/police-grid-denied.component.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/police-grid-inprogress/police-grid-inprogress.component.ts
- data was being fetched with case insensitive sort and the page/display was sorting sensitive,
> LCSD6437 - Added case insensitive sort to frontend for the 3 tables.

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/package.json
Reverts bcgov/jag-lcrb-carla-public#3755
> Revert "Updated browserlist to browserSlist"

- cllc-public-app/ClientApp/package-lock.json
Reverts bcgov/jag-lcrb-carla-public#3754
> Revert "Updated package-lock"

- federal-reporting-service/FederalReportingController.cs
- federal-reporting-service/Readme.md
- federal-reporting-service/federal-reporting-service.csproj
Patching for Federal Reporting Service
> [LCSD-6471] Security Vulnerability Patching 

- cllc-public-app/ClientApp/src/app/components/home/home.component.html
- This also removed the old text as requested
> LCSD-6509:  Added alert to home page for PRS start date.

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#3771
> Revert "Updated to remove console logging and comments"

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/Controllers/EstablishmentsController.cs
- cllc-public-app/Controllers/LicensesController.cs
Reverts bcgov/jag-lcrb-carla-public#3765
> Revert "Lcsd 6496"

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.html
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/Controllers/EstablishmentsController.cs
- cllc-public-app/Controllers/LicensesController.cs
Reverts bcgov/jag-lcrb-carla-public#3773
> Revert "Revert "Lcsd 6496""

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#3772
> Revert "Revert "Updated to remove console logging and comments""

- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
Re added "permanent-change-to-a-licensee/:applicationId/:invoiceType"
> Lcsd6490 - Updated app-routing-module

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
Implement disable multiple renewal and payment in two renewal component
> LCSD-6527 implement disable multiple renewal payment.

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
Reverts bcgov/jag-lcrb-carla-public#3798
> Revert "LCSD-6527 implement disable multiple renewal payment."

- cllc-public-app/openshift/templates/nginx-runtime/Dockerfile
Nginx image update to fix vulnerabilties
> Nginx image update to fix vulnerabilties

- cllc-public-app/openshift/templates/nginx-runtime/Dockerfile
Nginx image vulnerabilities fix
> Nginx image vulnerabilities fix

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
> LCSD-6553 Disable Submit and Pay button once clicked in application renewal and liquor renewal

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/proof-of-zoning/proof-of-zoning.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/proof-of-zoning/proof-of-zoning.component.ts
> LCSD-6483 Licensing - Lounge Endorsement Application - Zoning Declaration and Service Areas No longer Mandatory

- cllc-public-app/Controllers/FileController.cs
Removed Sub string from file URL in case entityName is account
> LCSD-6168 C&E Licensee unable to open enotification, Removed Sub string from file URL

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Remove the unneeded validation
> LCSD-6366 Licensing - Add new open descriptor for MFR Winery, Brewery & Distillery

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
LCSD-6366 Placing descriptor box within the MFR subclass declarations box
> LCSD-6366 Placing descriptor box within the MFR subclass declarations box

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/business-plan/business-plan.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/business-plan/business-plan.component.ts
- cllc-public-app/ClientApp/src/app/models/application.model.ts
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/ViewModels/Application.cs
Reverts bcgov/jag-lcrb-carla-public#3871
> Revert "LCSD-6344 Adding check boxes for manufacturer supporting information"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Reverts bcgov/jag-lcrb-carla-public#3870
> Revert "LCSD-6366 Placing descriptor box within the MFR subclass declarations box"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#3868
> Revert "LCSD-6366 Licensing - Add new open descriptor for MFR Winery, Brewery & Distillery"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/application.model.ts
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/ViewModels/Application.cs
Reverts bcgov/jag-lcrb-carla-public#3852
> Revert "LCSD-6355 Licensing - Lounge/SEA remove letter of intent, upload declarations"

- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/business-plan/business-plan.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/business-plan/business-plan.component.ts
- cllc-public-app/Controllers/PaymentController.cs
LCSD-6552 Handle cancel payment by adding new field PaymentCancelled
> LCSD-6552 Billing - Cancel on Bambora payment screen

- cllc-public-app/Controllers/PaymentController.cs
Reverts bcgov/jag-lcrb-carla-public#3898
> Revert "LCSD-6552 Billing - Cancel on Bambora payment screen"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
LCSD-6355 Adding the messing check box for Special Event Area Endorsement
> LCSD-6355 Licensing - Add new open descriptor for MFR Winery, Brewery & Distillery

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/Controllers/ApplicationsController.cs
Reverts bcgov/jag-lcrb-carla-public#3904
> Revert "LCSD6495 - Disabling This change until after Deploy."

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/Controllers/ApplicationsController.cs
Reverts bcgov/jag-lcrb-carla-public#3916
> LCSD6495 - Disabling This change until after March

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
- cllc-public-app/ClientApp/src/app/models/endorsement.model.ts
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/Endorsement.cs
- cllc-public-app/ViewModels/HoursOfService.cs
Reverts bcgov/jag-lcrb-carla-public#3924
> Revert "Revert "LCSD-6134 - C&E - TUA Event Authorization fixes required""

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
Reverts bcgov/jag-lcrb-carla-public#3942
> Revert "LCSD-6134 set maximum closing hours to 10 PM in case of outdoor event"

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
Reverts bcgov/jag-lcrb-carla-public#3929
> Revert "LSCD-6134 Fix Endorsement name"

- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.html
- cllc-public-app/ClientApp/src/app/components/federal-reporting/federal-reporting.component.ts
- cllc-public-app/ClientApp/src/app/services/monthly-report.service.ts
- cllc-public-app/Controllers/MonthlyReportsController.cs
Reverts bcgov/jag-lcrb-carla-public#3931
> Revert "Revert "LCSD-6499 C&E - Federal Reporting Page Performance Increase""

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
- cllc-public-app/ClientApp/src/app/models/endorsement.model.ts
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/Endorsement.cs
- cllc-public-app/ViewModels/HoursOfService.cs
Reverts bcgov/jag-lcrb-carla-public#3946
> Revert "Revert "Revert "Revert "LCSD-6134 - C&E - TUA Event Authorization fixes required""""

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
Reverts bcgov/jag-lcrb-carla-public#3945
> Revert "Revert "LSCD-6134 Fix Endorsement name""

- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.ts
Reverts bcgov/jag-lcrb-carla-public#3944
> Revert "Revert "LCSD-6134 set maximum closing hours to 10 PM in case of outdoor event""

- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/models/license-type.model.ts
Fixing the issue of Marketing Licence to allow renewal page to open
> LCSD-6556 Licensing - Marketing Licence Renewal Error

- one-stop-service/OneStopUtils.cs
Including LicenseeBn9Changed, LicenseeBn9Added and LicenseeBn9Removed
> LCSD-5745 OneStop - Manufacturer Lounge Approval

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
in application types Temporary Delicensing and Temporary Patron Participation Entertainment Endorsement id opened by LG account or if they have LG approval
> LCSD-6397 Disable editing the application fields for LG user and after LG approval

- cllc-public-app/Controllers/AccountsController.cs
- cllc-public-app/Controllers/PDFConverterController.cs
- cllc-public-app/cllc-public-app.csproj
> LCSD-6539 - Adding an API to convert word to PDF

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Showing Start date/End date only for Temporary Suspension and Temporary Patron Participation Entertainment Endorsement applications.
> LCSD-6397 Showing Start date/End date only for Temp Suspension and Temporary Patron

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
… type Temporary Change to a Liquor Licence - Other)"
-Reverting as NOT releasing to PROD at this time.   More work to do.
> Revert "LCSD-6391 - Adding the application type Temporary Change to a Liquor Licence - Other"

- .github/workflows/cd-orgbook-service.yml
- cllc-interfaces/Dynamics-Autorest/Models/MicrosoftDynamicsCRMadoxioServicearea.cs
- cllc-interfaces/Dynamics-Autorest/dynamics-swagger.json
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
- cllc-public-app/ClientApp/src/app/models/service-area.model.ts
- cllc-public-app/Controllers/ApplicationsController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Models.Extensions/CapacityArea.cs
- cllc-public-app/ViewModels/CapacityArea.cs
- orgbook-service/Startup.cs
Reverts bcgov/jag-lcrb-carla-public#4011
> Revert "Merging develop to master for UAT (LCSD-6646  LCSD-6624 LCSD-6416)"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
- cllc-public-app/ClientApp/src/app/models/service-area.model.ts
- cllc-public-app/Controllers/ApplicationsController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/Models.Extensions/CapacityArea.cs
- cllc-public-app/ViewModels/CapacityArea.cs
Reverts bcgov/jag-lcrb-carla-public#4019
> Revert "Revert "LCSD-6416 - Hiding the Temporary Extension Area from the lice…"

- orgbook-service/Startup.cs
Reverts bcgov/jag-lcrb-carla-public#4008
> Revert "LCSD-6624 - Change the timing for services"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Reverts bcgov/jag-lcrb-carla-public#4023
> Reverting again "LCSD-6391 - Adding the application type Temporary Change to a Liquor Licence - Other""" Not ready for deploy

- orgbook-service/Startup.cs
Reverts bcgov/jag-lcrb-carla-public#4026
> Changing Back "LCSD-6624 - Change the timing for services""

- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Reverts bcgov/jag-lcrb-carla-public#4046
> Revert "Merging to develop to master for LCSD 6459"

- cllc-public-app/Utils/StatusUtility.cs
Keep the application status as Submitted to match Dynamics status
> LCSD-6737 Keep the application as Subitted to match Dynamics status

- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Reverts bcgov/jag-lcrb-carla-public#4049
> "Re-Merging from develop to master for LCSD 6459""

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Pushing Changes for 6886 back into master
> Re-Merging develop to master for UAT (LCSD-6886) 

- cllc-interfaces/BCeID/BCeIDBasic.cs
- cllc-interfaces/BCeID/BCeIDBusinessQuery.cs
- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/Controllers/AccountsController.cs
- cllc-public-app/Controllers/UserController.cs
instead of siteminder header when logging in or creating account or registering new user.
> LCSD-6488: Updated to fetch firstname and lastname via bceid webquery. 

- cllc-interfaces/Dynamics-Autorest/Models/MicrosoftDynamicsCRMadoxioApplication.cs
Reverts bcgov/jag-lcrb-carla-public#4060
> Revert "LCSD-6743 Regenerating the new fields, adding application fields"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/styles.scss
Reverts bcgov/jag-lcrb-carla-public#4077
> Revert "Merging develop to master for UAT (LCSD-6743 Update3) "

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Reverts bcgov/jag-lcrb-carla-public#4074
> Revert "Merging develop to master for UAT (LCSD 6743 Update2) "

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#4072
> Revert "Merging develop to master for UAT (LCSD-6743 Update)"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#4080
> Revert "Revert "Merging develop to master for UAT (LCSD-6743 Update)""

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Reverts bcgov/jag-lcrb-carla-public#4079
> Revert "Revert "Merging develop to master for UAT (LCSD 6743 Update2) ""

- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/forbidden-modal/forbidden-modal.component.html
- cllc-public-app/ClientApp/src/app/shared/components/forbidden-modal/forbidden-modal.component.spec.ts
- cllc-public-app/ClientApp/src/app/shared/components/forbidden-modal/forbidden-modal.component.ts
…t deep-linking to /application page
> LCSD-6243 Created new Forbidden modal page as part of logic to prevent deep-linking to /application page

- cllc-interfaces/BCeID/BCeIDBasic.cs
- cllc-interfaces/BCeID/BCeIDBusinessQuery.cs
- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/Controllers/AccountsController.cs
- cllc-public-app/Controllers/UserController.cs
Reverts bcgov/jag-lcrb-carla-public#4084
> Reintegrating "Merging develop to master for UAT (LCSD-6488)""

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Reverts bcgov/jag-lcrb-carla-public#4135
> Revert "LCSD-6243 Fix unable to click on Resolve Incompleteness link"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Reverts bcgov/jag-lcrb-carla-public#4138
> Reintegrating "LCSD-6243 Fix unable to click on Resolve Incompleteness link""

- orgbook-service/Controllers/OrgBookController.cs
Updating OrgBook links for licencee and licence to navigate to the right page in OrgBook.
> LCSD-6958 - Updating OrgBook links 

- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/applications/application-tied-house-exemption/application-tied-house-exemption.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-tied-house-exemption/application-tied-house-exemption.component.ts
- cllc-public-app/ClientApp/src/app/models/related-licence.ts
- cllc-public-app/ClientApp/src/app/services/application-data.service.ts
- cllc-public-app/ClientApp/src/app/shared/components/related-jobnumber-picker/related-jobnumber-picker.component.html
- cllc-public-app/ClientApp/src/app/shared/components/related-jobnumber-picker/related-jobnumber-picker.component.spec.ts
- cllc-public-app/ClientApp/src/app/shared/components/related-jobnumber-picker/related-jobnumber-picker.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/related-licence-picker/related-licence-picker.component.html
- cllc-public-app/ClientApp/src/app/shared/components/related-licence-picker/related-licence-picker.component.ts
- cllc-public-app/Controllers/ApplicationsController.cs
- cllc-public-app/Controllers/LicensesController.cs
- cllc-public-app/ViewModels/RelatedLicence.cs
Added a note to indicate that JobNumber searches only include Applications with Assigned Licences.
> LCSD-6368 Added note verbiage to JobNumber search

- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.scss
Reverts bcgov/jag-lcrb-carla-public#4147 as this will not be part of LCRB DevOps Release 7.0.41
> Removing "Merging Develop to Master for UAT (LCSD 6163)" for LCRB DevOps Release 7.0.41

- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/components/sep/dashboard/dashboard.component.scss
Reverts bcgov/jag-lcrb-carla-public#4153
Merging this removed change back into master to remove conflicts with Develop branch. Will merge back in once Develop is up to date.
> Revert "Removing "Merging Develop to Master for UAT (LCSD 6163)" for LCRB DevOps Release 7.0.41"

- cllc-interfaces/BCeID/BCeIDBasic.cs
- cllc-interfaces/BCeID/BCeIDBusinessQuery.cs
- cllc-public-app/Authentication/SiteminderAuthenticationHandler.cs
- cllc-public-app/Controllers/AccountsController.cs
- cllc-public-app/Controllers/UserController.cs
Reverts bcgov/jag-lcrb-carla-public#4152
Merging this removed change back into master to remove conflicts with Develop branch. Will merge back in once Develop is up to date.
> Revert "Removing "Merging develop to master for UAT (LCSD-6488)" for LCRB DevOps Release 7.0.41"

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.scss
- cllc-public-app/ClientApp/src/app/app.component.ts
Added chat feature to CARLA. Most of the changes in the diff are from my Prettier auto-formatter.
> LCSD-7130: Add "chat with us" chat button

- cllc-public-app/Models.Extensions/License.cs
* LCSD-7127
* Update for coding practices
> Merge develop to master for UAT ( LCSD-7127) for LCRB DevOps Release 7.0.45

- cllc-public-app/Models.Extensions/License.cs
One-line patch - forgot to add variable type to dayClosedValue when completing LCSD-7127.
> LCSD-7127: Fix for PDF generation issue.  Update variable declaration

- cllc-public-app/Models.Extensions/License.cs
Fixed variable declaration error
> Merge develop to master for UAT ( LCSD-7127) for LCRB DevOps Release 7.0.45, Fix minor syntax error

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/Models.Extensions/Account.cs
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/Account.cs
Last-minute patch to temporarily disable work done to add account URL field to application.
> LCSD-7126 : Patch - Hide account URL field for release 7.0.45

- cllc-public-app/Controllers/ApplicationsController.cs
…Outside Service Hours)) (#4178)
> LCSD-5744:  Merge develop to  master for release 7.0.46 -  Licensing - Change to Hours

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-6186
Changed string text on a date warning
> LCSD-6186: SEP - Alert Message needs to be re-worded

- cllc-public-app/ClientApp/src/app/components/police-representative/police-summary/police-summary.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/models/sep-schedule.model.ts
LCSD-7141 - Convert User Enter Time into PST
reworked event.component html/ts to have a Pacific/Mountain radio button.  Times are now converted to UTC before being sent to backend, and if mountain is selected, UTC time has an hour subtracted to reflect equivalent Pacific time.
> LCSD-7141: Convert User Enter Time into PST

- package.json
Reverts bcgov/jag-lcrb-carla-public#4193
> Revert "LCSD-7141: Convert User Enter Time into PST 3"

- .github/workflows/cd-portal-build-dev.yaml
- .gitignore
Remove extra jobs key
Add version to actions
Add project command
Update to node 20
Comment lines
Update
Rename
Remove node20 step
> Add Github Action for Development Build

- cllc-interfaces/BCEP/BCEPService.cs
Reverts bcgov/jag-lcrb-carla-public#4206
> Revert "LCSD-7153: Update GET to POST for /process_transaction.asp"

- cllc-public-app/ClientApp/src/app/components/applications/application-tied-house-exemption/application-tied-house-exemption.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#4151
> Revert "LCSD-7008: Do not display "Submit & Pay" button on /application form if Generate Invoice=Yes"

- cllc-interfaces/BCEP/BCEPService.cs
Reverts bcgov/jag-lcrb-carla-public#4212
Not going into this release.
> Revert "LCSD-7153: PCIR Implementation" - SAVE for later release

- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7190
Just minor text changes to an html page.
> LCSD-7190 - Policy - LIQ - Market Authorization / Craft Distilleries - Minor Content Change on Portal

- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
…- Minor Content Change on Portal (#4216)
> Merge to master:  LCSD-7190 - Policy - LIQ - Market Authorization / Craft Distilleries

- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
…- Minor Content Change on Portal (2G)
> LCSD-7190 - Minor Text change

- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
LCSD-7190 - Policy - LIQ - Market Authorization / Craft Distilleries - Minor Content Change on Portal (2G)
> Merge to master: LCSD-7190 - Minor Text change (#4220)

- cllc-public-app/ClientApp/src/app/app.component.html
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7244
Just adding an outage banner to portal
> LCSD-7244 - Banner on the Portal

- cllc-public-app/ClientApp/src/app/components/applications/application-tied-house-exemption/application-tied-house-exemption.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Reverts bcgov/jag-lcrb-carla-public#4218
> Revert "Merge to master: LCSD-7008: Do not display "Submit & Pay"  if invoices requested"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/Models.Extensions/Application.cs
ticket: not provided
NOTE: this has not been locally tested
> LCSD-7200-4 - Guided Testing Followup

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/Models.Extensions/Application.cs
> LCSD-7200-5 - Guided Testing Followup 3

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/Models.Extensions/Application.cs
> LCSD-7200-6 - Guided Testing Followup 6

- cllc-public-app/ClientApp/src/app/components/police-representative/police-summary/police-summary.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/models/sep-schedule.model.ts
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7141
- added radio buttons to note pacific or mountain in event form
- adjusted how time is handled to always show pacific
-  made it such that whichever time is selected, pacific converted to UTC is always what is stored
> LCSD-7141 - Convert User Enter Time into PST

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7241
Added disabled and readonly tags to relevant elements
> LCSD-7241 - Make Business Number and Incorporation Number as Read-Only

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/package.json
- cllc-public-app/ClientApp/src/app/components/police-representative/police-summary/police-summary.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/models/sep-schedule.model.ts
ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7141
> LCSD-7141 - Convert User Entered Time into PST (3)

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/Models.Extensions/Account.cs
- cllc-public-app/ViewModels/Account.cs
Quick PR to un-comment account URL support for upcoming demo.
> Re-enable Account URLs on Business Profile

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/Models.Extensions/Application.cs
This PR adds back the previously removed Proof of Valid Interest section to the Dormancy Reinstatement form.
> LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement form

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
Disabling ORV feature in the account profile until further dev work can be completed to support this feature.
> Hide ORV Feature

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
[Tied House-LE Portal System Changes - PHASE ONE.docx](https://github.com/user-attachments/files/17033252/Tied.House-LE.Portal.System.Changes.-.PHASE.ONE.docx)
> Conditionally hide directors and officers notice

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Additional work completed following feedback on initial implementation:
- Hide notice on Third Party Operator application
- Hide notice on Liquor License Transfer application
- Hide notice on Permanent Change to a Licensee - Change of Directors or Officers
> Hide directors officers notice (Patch)

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/package.json
- cllc-public-app/ClientApp/src/app/app-routing.module.ts
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.scss
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/tabs/proof-of-zoning/proof-of-zoning.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/licences/licence-row/licence-row.component.ts
- cllc-public-app/ClientApp/src/app/components/police-representative/police-summary/police-summary.component.ts
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.html
- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/ClientApp/src/app/models/application-license-summary.model.ts
- cllc-public-app/ClientApp/src/app/models/sep-schedule.model.ts
- cllc-public-app/ClientApp/src/environments/environment.ts
- cllc-public-app/Models.Extensions/Account.cs
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/Models.Extensions/License.cs
- cllc-public-app/ViewModels/Account.cs
- cllc-public-app/ViewModels/ApplicationLicenseSummary.cs
Replace features removed for special release 7.0.54&55
> Re-Merge to Master: LCSD-7141,7126,7329,7328,7327,7275,7312 

- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
Quick change to break out of the loop if we find a matching record and remove a console log that made it through the last review.
> LCSD-7328-Optimization: Remove console log, break out of loop

- cllc-public-app/ClientApp/src/app/components/relocation-type/relocation-type.component.ts
Added "Intake" to the fields to consider when disabling a temporary relocation by its status.
> LCSD-7328-Patch-2: Add intake to list of fields to consider

- cllc-public-app/ClientApp/src/app/components/police-representative/police-summary/police-summary.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/event/event.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/models/sep-schedule.model.ts
Revert changes made in timezone ticket for upcoming release.
> Revert Timezone Changes

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/Models.Extensions/Application.cs
Reverts bcgov/jag-lcrb-carla-public#4275
> Revert "LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement form"

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/Models.Extensions/Application.cs
…tatement form" (#4291)
Revert "LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement…"
This reverts commit c94ebfdd9597a250dea4a385cde1ee7725bb6a11.
> Revert "LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement

- cllc-public-app/ClientApp/src/app/app.component.html
> Update banner text

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/tables/capacity-table.component.html
Licensing – CM Lean – Floor Plans – 1 of 2 – Occupant Load (Fillable field)
Licensing - LP/LPC/LP Location Change - Update Floor Plan Requirement Language (Occupant Load Stamp)
> LCSD-6857 LCSD-7322

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Ticket: https://jag.gov.bc.ca/jira/browse/LCSD-7312
> LCSD-7312: Add proof of valid interest back to dormancy reinstatement

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-renewal/application-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/drink-planner/drink-planner.component.html
- cllc-public-app/ClientApp/src/app/components/sep/drink-planner/drink-planner.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.scss
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
- cllc-public-app/ClientApp/src/app/components/sep/starter-checklist/starter-checklist.component.html
- cllc-public-app/ClientApp/src/app/components/tables/capacity-table.component.html
* Revert "LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement form" (#4291)
Revert "LCSD-7312: Add proof of valid interest back to Dormancy Reinstatement…"
This reverts commit c94ebfdd9597a250dea4a385cde1ee7725bb6a11.
* LCSD-7367 (#4294)
SEP Application: Portion size is not getting calculated for free servings
* LCSD-7483: Add banner for dynamics upgrade (#4296)
* Add banner text for dynamics outage
* Update banner text
* LCSD-6147 (#4298)
* LCSD-6147
SEP Checklist, add permit holder's responsibilities.
* Update banner text (#4297)
* LCSD-6857 LCSD-7322 (#4300)
LCSD-6857 & LCSD-7322
Licensing - LP/LPC/LP Location Change - Update Floor Plan Requirement Language (Occupant Load Stamp)
Licensing – CM Lean – Floor Plans – 1 of 2 – Occupant Load (Fillable field)
* LCSD-7413 …
> Merge to Master: LCSD 6147, 7312, 7235, 6857, 7322, 7367, 6465 (#4306)

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application-licensee-changes/application-licensee-changes.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-an-applicant/permanent-change-to-an-applicant.component.html
- cllc-public-app/ClientApp/src/app/components/cannabis-associate-screening/cannabis-associate-screening.component.html
- cllc-public-app/ClientApp/src/app/components/catering-event/catering-event-form.component.html
- cllc-public-app/ClientApp/src/app/components/liquor-free-event/liquor-free-event.component.html
- cllc-public-app/ClientApp/src/app/components/market-event/market-event.component.html
- cllc-public-app/ClientApp/src/app/components/offsite-storage/offsite-storage.component.html
- cllc-public-app/ClientApp/src/app/components/personal-history-summary/personal-history-summary.component.html
- cllc-public-app/ClientApp/src/app/components/servicecard-profile/servicecard-profile.component.html
- cllc-public-app/ClientApp/src/app/components/take-home-event/take-home-event.component.html
- cllc-public-app/ClientApp/src/app/components/temporary-offsite/temporary-offsite.component.html
- cllc-public-app/ClientApp/src/app/components/tua-event/tua-event.component.html
- cllc-public-app/ClientApp/src/app/models/account.model.ts
https://jag.gov.bc.ca/jira/browse/LCSD-7032
https://jag.gov.bc.ca/jira/browse/LCSD-6661
https://jag.gov.bc.ca/jira/browse/LCSD-7499
> LCSD-7032, 6661, 7499: Correct Grammatical Error in CARLA, fix typo, update Collection Notice

- cllc-public-app/Startup.cs
https://jag.gov.bc.ca/jira/browse/LCSD-7391
> LCSD-7391: Increase gRPC Message Size Limit

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Revert "LCSD-7008 (#4330)"
This reverts commit 02f474338fc597a0c0f59e1420a2326676185ba6.
> Revert "LCSD-7008" (#4334)

- cllc-public-app/ClientApp/src/app/components/applications/application-tied-house-exemption/application-tied-house-exemption.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
Change label text for MFR production amount as requested. Also remove read-only conditional check for the input field.
> LCSD-6492 Tied House Exemption label text change

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/sep/drink-planner/drink-planner.component.html
- cllc-public-app/Controllers/SpecialEventsController.cs
https://jag.gov.bc.ca/jira/browse/LCSD-7524
https://jag.gov.bc.ca/jira/browse/LCSD-7304
https://jag.gov.bc.ca/jira/browse/LCSD-6363
> LCSD-7524, 7304, 6363: Update SEP banner formatting, Add 'Outdoor Event Venue' Establishment Type, Filter Police Review Queue

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
- cllc-public-app/ClientApp/src/app/models/geocoder.model.ts
- cllc-public-app/ClientApp/src/app/services/geocoder.service.ts
- cllc-public-app/Controllers/GeocoderController.cs
[LCSD-7535](https://jag.gov.bc.ca/jira/browse/LCSD-7535) Fetch PID from DataBC civic address APIs
> LCSD-7535 Added support to fetch PID from DataBC

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.scss
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.html
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.scss
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.ts
- cllc-public-app/ClientApp/src/app/services/feedback.service.ts
- cllc-public-app/Controllers/FeedbackController.cs
- cllc-public-app/Controllers/GeocoderController.cs
LCSD-7512
Add feedback component and service for user feedback submission
>   LCSD-7512

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.scss
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/app/app.module.ts
- cllc-public-app/ClientApp/src/app/components/applications/liquor-renewal/liquor-renewal.component.html
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.html
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.scss
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.spec.ts
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.ts
- cllc-public-app/ClientApp/src/app/services/feedback.service.ts
- cllc-public-app/Controllers/FeedbackController.cs
- cllc-public-app/Controllers/GeocoderController.cs
> Merge to Master

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-an-applicant/permanent-change-to-an-applicant.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-an-applicant/permanent-change-to-an-applicant.component.ts
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.html
Content changes and added links to reference documents
> LCSD 7463 licensing CM Lean

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/environments/environment.prod.ts
- cllc-public-app/ClientApp/src/environments/environment.ts
https://jira.justice.gov.bc.ca/browse/LCSD-7494
> LCSD-7494 Dynamic Maintenance Banner

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-an-applicant/permanent-change-to-an-applicant.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-an-applicant/permanent-change-to-an-applicant.component.ts
- cllc-public-app/ClientApp/src/app/components/feedback/feedback.component.html
- cllc-public-app/ClientApp/src/environments/environment.prod.ts
- cllc-public-app/ClientApp/src/environments/environment.ts
> Merge to master LCSD 7463 LCSD-7494

- cllc-public-app/ClientApp/src/app/app.component.html
- cllc-public-app/ClientApp/src/app/app.component.ts
- cllc-public-app/ClientApp/src/assets/banner-config.json
- cllc-public-app/ClientApp/src/environments/environment.prod.ts
- cllc-public-app/ClientApp/src/environments/environment.ts
> Merge to Master LCSD-7494

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Show sample floor plan, same as the one for FP, for the following LP/LPC applications:
- new LP
- new LPC
- Relocation
- Patio
- LP structural (cap inc.)
- LP structural (no cap inc.)
> LCSD-5856 sample floor plans for LP/LPC appls

- cllc-public-app/ClientApp/src/app/components/sep/drink-planner/drink-planner.component.ts
- cllc-public-app/Controllers/SpecialEventsController.cs
Enabled Combination of drink type (free + paid) for Charity event
> LCSD-7598 Enabled Combination of drink type (free + paid) for Charity event 

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
https://jira.justice.gov.bc.ca/browse/LCSD-7734
Simple text update.
> LCSD-7734: Update CRS checkbox text

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/sep-application.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/sep-application.component.ts
- cllc-public-app/Controllers/SpecialEventsController.cs
LCSD-7757 disable update SEP application from portal once application is submitted
> LCSD-7757 disable update SEP application from portal once application is submitted

- cllc-public-app/Controllers/LogoutController.cs
Cleared SMSESSION Cache on logout
> LCSD-6488   Licensing - Primary Contact Error

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/models/application-type.model.ts
Change to Hours of Liquor Service (Lounge Area, outside Service Hours)
Change to Hours of Liquor Service (Special Event Area, within Service Hours)
> Lcsd 5881 Licensing - Add discretion app info and toggle on permanent hours change applications

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.scss
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/README.md
https://jira.justice.gov.bc.ca/browse/LCSD-7793
New UI control for the `Account URL(s)` field on the user's Profile page. Splits the single comma-separated account urls string into multiple form fields.
I sent a demo video of the UI to Ryan earlier, he had no notes.
> LCSD-7793: New UI controls for adding/editing account urls.

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-7793
Fix a bug that caused the account urls to not load into the form properly.
- The original change was made before I had my AG IDIR, so I had to bypass the API and fake the data. Evidently I didn't mock the api data quite right. Became apparent after it was merged to Dev, and wasn't working as expected.
Updated the valid urls regex slightly. There seemed to be some issues with slash escape characters, and it was letting some odd strings through the validation.
On the Account Profile page, a user's existing account urls should now load properly.
> BugFix: AccountURLs not properly loading in the form.

- cllc-public-app/Controllers/LogoutController.cs
> Lcsd 7182 first last name mapping error

- cllc-interfaces/Dynamics-Autorest/ModelExtensions/OneStopHubStatusChangeType.cs
- one-stop-service/OneStopUtils.cs
Reverts bcgov/jag-lcrb-carla-public#4409
> Revert "LCSD-6537 Onestop send account broadcast error"

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
> Merge to Master LCSD-7412 (#4419)

- cllc-public-app/ClientApp/package-lock.json
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.scss
- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.ts
- cllc-public-app/ClientApp/src/app/models/account.model.ts
- cllc-public-app/README.md
https://jira.justice.gov.bc.ca/browse/LCSD-7793
Add new UI control for the "Account Urls" section of the account page in the portal.
You should be able to view/add/edit/remove multiple Account Urls, each in their own field in the UI.
The API is unchanged.
This is a PR to re-add this code, if and when its ready, after it was [reverted in this PR.](https://github.com/bcgov/jag-lcrb-carla-public/pull/4406)
> LCSD-7793: Change Licensee URL's to Editable List in Portal

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
> Merge to Master: LCSD-7801

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.html
- cllc-public-app/ClientApp/src/app/components/sep/sep-application/summary/summary.component.ts
LCSD-7976-2 (continuation of LCSD-7976)
> Merge to Master: LCSD-7976-2

- cllc-public-app/ClientApp/src/app/components/sep/sep-application/liquor/liquor.component.html
On the Liquor Overview page for SEP application, update text for drink estimation, and add local Police review information.
> LCSD-8010 SEP drink estimate content update (#4452)

- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.html
- cllc-public-app/ClientApp/src/app/components/applications/application/application.component.ts
Merge mater into develop to resolve conflicts.
Resolve conflicts between develop and master.
> LCSD-7940 - Tied House Feature - 5

- cllc-interfaces/Dynamics-Autorest/Extensions/DynamicsClient.cs
- cllc-public-app/ClientApp/src/app/components/applications/legal-entity-review-permanent-change-to-a-licensee/legal-entity-review-permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-payment/permanent-change-payment.component.html
- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-payment/permanent-change-payment.component.ts
- cllc-public-app/Controllers/ApplicationsController.cs
- cllc-public-app/Controllers/PaymentController.cs
https://jira.justice.gov.bc.ca/browse/LCSD-7940 (epic)
- Updates to how PCL invoices are handled when the invoice amount is $0.
- Fixed some funny formatting issues
- Updated some error messaging to be more clear
- Fixed the "New Application" button at the bottom of the PCL page.
> LCSD-7940 - Tied House Feature - 7

- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/models/application.model.ts
- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-payment/permanent-change-payment.component.html
- cllc-public-app/Controllers/ApplicationsController.cs
- cllc-public-app/Models.Extensions/Application.cs
- cllc-public-app/ViewModels/Application.cs
https://jira.justice.gov.bc.ca/browse/LCSD-7940 (epic)
- Minor bug fixes
> LCSD-7940 - Tied House Feature - 8

- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.html
- cllc-public-app/Models.Extensions/AdoxioTiedHouseConnections.cs
https://jira.justice.gov.bc.ca/browse/LCSD-7940
> Merge to Master: LCSD-7940

- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.html
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.ts
Show accordion validation for editing th connection
> LCSD-8059: TH-UAT-Bug-edit-th-component-validation

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/pcl-business-rules/pcl-bussiness-rules-types.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/pcl-business-rules/pcl-bussiness-rules-utils.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.html
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/applications-and-licences/applications-and-licences.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/dashboard.component.html
- cllc-public-app/ClientApp/src/app/components/dashboard/dashboard.component.ts
- cllc-public-app/ClientApp/src/app/components/dashboard/legal-entity-type-update-calloutbox/legal-entity-type-update-calloutbox.component.html
- cllc-public-app/ClientApp/src/app/components/dashboard/legal-entity-type-update-calloutbox/legal-entity-type-update-calloutbox.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-8069
https://jira.justice.gov.bc.ca/browse/LCSD-8082
> Merge to Master: LCSD-8069-2, LCSD-8082

- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-other-liquor-licences/connection-to-other-liquor-licences.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-other-liquor-licences/connection-to-other-liquor-licences.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/legal-entity-review/legal-entity-review.component.html
- cllc-public-app/ClientApp/src/app/components/applications/legal-entity-review/legal-entity-review.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/legal-entity-review/legal-entity-review-supporting-documents/legal-entity-review-supporting-documents.component.html
- cllc-public-app/ClientApp/src/app/shared/components/legal-entity-review/legal-entity-review-supporting-documents/legal-entity-review-supporting-documents.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-7940
- Some misc cleanup of existing code.
- Add improved mechanism (output event) to allow parent components to force-show the tied house component, if a new record is added, etc.
- Some additional wording changes to documents component.
> LCSD-7940: Tied House Misc Fixes/Cleanup

- cllc-public-app/ClientApp/src/app/shared/components/legal-entity-review/legal-entity-review-supporting-documents/legal-entity-review-supporting-documents.component.html
https://jira.justice.gov.bc.ca/browse/LCSD-8098
- Update LE Review Document prefix type from "NOA" to "LER".
- Update LE Review Document text.
> LCSD-8098: Misc Tied House Updates.

- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tide-house-utils.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.ts
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.html
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.scss
- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-decleration-form/tied-house-declaration-form.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/field/field.component.html
- cllc-public-app/ClientApp/src/app/shared/date-adapter.ts
- cllc-public-app/ClientApp/src/app/shared/date-fns.ts
- https://jira.justice.gov.bc.ca/browse/LCSD-8102
- https://jira.justice.gov.bc.ca/browse/LCSD-8103
Update the tied house date picker logic/css.
- Resolve off-by-1 issue reported in bug.
- Displays dates in "YYYY-MM-DD" format.
> LCSD-8103: TH-UAT2-Bug-1

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/pcl-business-rules/pcl-bussiness-rules-utils.ts
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.html
- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/permanent-change-to-a-licensee.component.ts
- cllc-public-app/ClientApp/src/app/shared/components/legal-entity-review/legal-entity-review-types-of-changes-required/legal-entity-review-types-of-changes-required.component.html
https://jira.justice.gov.bc.ca/browse/LCSD-8105
Fix odd casing of "Of".
Fix incorrect variable name in html.
> LCSD-8105-2: Misc Fixes

- cllc-public-app/ClientApp/src/app/shared/components/permanent-change/permanent-change-cannabis-security-screening-forms/permanent-change-cannabis-security-screening-forms.component.html
https://jira.justice.gov.bc.ca/browse/LCSD-8109
Old link returns a 404. Now we use a redirect for the correct page.
> LCSD-8109: Update broken external link

- cllc-public-app/ClientApp/src/app/components/account-profile/account-profile.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.html
- cllc-public-app/ClientApp/src/app/components/account-profile/tabs/connection-to-producers/connection-to-producers.component.ts
https://jira.justice.gov.bc.ca/browse/LCSD-8114
Add logic to toggle the editability of the Cannabis tied house section on the account review page.
> LCSD-8114: TH-UAT3-Bug-2

- cllc-public-app/ClientApp/src/app/components/applications/permanent-change-to-a-licensee/pcl-business-rules/pcl-bussiness-rules-utils.ts
https://jira.justice.gov.bc.ca/browse/LCSD-8115
Add Local Government to PCL Matrix rules, as per latest version of matrix excel file uploaded to https://jira.justice.gov.bc.ca/browse/LCSD-8111
> LCSD-8115: TH-UAT3-Bug-3

- cllc-public-app/ClientApp/src/app/components/applications/tied-house-decleration/tied-house-declaration.component.html
- cllc-public-app/ClientApp/src/app/shared/components/legal-entity-review/legal-entity-review-job/legal-entity-review-job.component.html
> LCSD-8127: TH instructional message
